// imageAssets.js
export const icons = {
  arrowBack: require("@/assets/icons/arrow-back.png"),
  arrowDown: require("@/assets/icons/arrow-down.png"),
  arrowRight: require("@/assets/icons/arrow-right.png"),
  bag: require("@/assets/icons/bag.png"),
  check: require("@/assets/icons/check.png"),
  clock: require("@/assets/icons/clock.png"),
  dollar: require("@/assets/icons/dollar.png"),
  envelope: require("@/assets/icons/envelope.png"),
  home: require("@/assets/icons/home.png"),
  location: require("@/assets/icons/location.png"),
  logout: require("@/assets/icons/logout.png"),
  minus: require("@/assets/icons/minus.png"),
  pencil: require("@/assets/icons/pencil.png"),
  person: require("@/assets/icons/person.png"),
  phone: require("@/assets/icons/phone.png"),
  plus: require("@/assets/icons/plus.png"),
  search: require("@/assets/icons/search.png"),
  star: require("@/assets/icons/star.png"),
  trash: require("@/assets/icons/trash.png"),
  user: require("@/assets/icons/user.png"),
};

export const images = {
  avatar: require("@/assets/images/avatar.png"),
  avocado: require("@/assets/images/avocado.png"),
  bacon: require("@/assets/images/bacon.png"),
  burgerOne: require("@/assets/images/burger-one.png"),
  burgerTwo: require("@/assets/images/burger-two.png"),
  buritto: require("@/assets/images/buritto.png"),
  cheese: require("@/assets/images/cheese.png"),
  coleslaw: require("@/assets/images/coleslaw.png"),
  cucumber: require("@/assets/images/cucumber.png"),
  emptyState: require("@/assets/images/empty-state.png"),
  fries: require("@/assets/images/fries.png"),
  loginGraphic: require("@/assets/images/login-graphic.png"),
  logo: require("@/assets/images/logo.png"),
  mozarellaSticks: require("@/assets/images/mozarella-sticks.png"),
  mushrooms: require("@/assets/images/mushrooms.png"),
  onionRings: require("@/assets/images/onion-rings.png"),
  onions: require("@/assets/images/onions.png"),
  pizzaOne: require("@/assets/images/pizza-one.png"),
  salad: require("@/assets/images/salad.png"),
  success: require("@/assets/images/success.png"),
  tomatoes: require("@/assets/images/tomatoes.png"),
};
